export default [
    {
        id:1,
        name:'Programming',
        icon:'/coading.webp',
        prompt:'',
    },
    {
        id:2,
        name:'Health',
        icon:'/health.png',
        prompt:'',
    },
    {
        id:3,
        name:'Creative',
        icon:'/creative.avif',
        prompt:'',
    },
]